version: "3"

services:
  web:
    image: test_app
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: test_app
    volumes:
      - .:/test_app
    links:
      - mongodb:mongodb
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATBASE: excel_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8%*jC5Iu@fNq
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: